name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Navigate to `assignment4_starter_code` and install dependencies
      - name: Install dependencies
        run: |
          cd assignment4_starter_code
          python3 -m venv venv  # Create a virtual environment
          . ./venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # 4. Run the Flask application in the background
      - name: Run the application
        run: |
          cd assignment4_starter_code
          . ./venv/bin/activate  # Activate the virtual environment
          make run &  # Run the app (assumes `make run` works in your Makefile)
          sleep 10  # Wait for the server to start

      # 5. Check if the server is running
      - name: Check if the server is running
        run: |
          curl --fail http://localhost:3000 || exit 1

      # 6. Lint the code with flake8
      - name: Lint with flake8
        run: |
          cd assignment4_starter_code
          . ./venv/bin/activate  # Activate the virtual environment
          pip install flake8  # Ensure flake8 is installed
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv
