name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Navigate to the directory and install dependencies using Makefile
      - name: Install dependencies
        run: |
          cd assignment4_starter_code  # Navigate to the folder with the Makefile
          make install  # This will run `make install` to set up the virtual environment and install dependencies

      # 4. Navigate to the directory and run the Flask application in the background
      - name: Run the application
        run: |
          cd assignment4_starter_code  # Navigate to the folder with the Makefile
          make run &  # This will run the Flask application in the background
          sleep 10  # Give the server some time to start

      # 5. Check if the server is running
      - name: Check if the server is running
        run: |
          curl --fail http://localhost:3000 || exit 1

      # 6. Lint the code with flake8
      - name: Lint with flake8
        run: |
          cd assignment4_starter_code  # Navigate to the folder with the Makefile
          . venv/bin/activate  # Activate the virtual environment
          pip install flake8  # Ensure flake8 is installed
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv
