name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies using Makefile inside the correct folder
      - name: Install dependencies
        run: |
          cd assignment4_starter_code
          python3 -m venv venv  # Ensure correct venv path
          . ./venv/bin/activate
          make install

      # 4. Run the application in the background
      - name: Run the application
        run: |
          cd assignment4_starter_code
          make run &
          sleep 10  # Give the server some time to start

      # 5. Check if the server is running
      - name: Check if server is running
        run: |
          curl --fail http://localhost:3000 || exit 1

      # 6. Lint the code with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv
